### ISSUE TITLE
Null Reference Exception when Loading Library

### ISSUE THREAD

**Issue by CoryParsnipson** [kamyker/supabase-unity#3]
Hi, I'm trying to use this library in my Unity project and when I instantiate it, I get a NullReferenceException because of the GetAssemblyVersion() helper function:

`.Submodules\supabase-csharp\Supabase\Util.cs:13`

```
public static string GetAssemblyVersion()
        {
            var assembly = typeof(Supabase.Client).Assembly;
            var informationVersion = assembly.GetCustomAttribute<AssemblyInformationalVersionAttribute>().InformationalVersion;
            var name = assembly.GetName().Name;

            return $"{name.ToString().ToLower()}-csharp/{informationVersion}";
        }
```

Specifically, the `assembly.GetCustomAttribute<AssemblyInformationVersionAttribute>()` returns null.

I've tracked it down to the fact that in the latest commit, the pre-generated `Supabase.AssemblyInfo.cs` file was deleted.

The path of this file was `/Unity/supabase-cloned/supabase-csharp/Supabase/obj/Debug/netstandard2.0/Supabase.AssemblyInfo.cs` and the comments say that it is automatically generated by the build.

If I manually restore this file, the attributes are able to be retrieved as expected and everything works. If the file is missing, the `assembly` variable appears to have zero initialized files.

It looks like this file might have been removed by mistake, or if it was on purpose, then it should have been regenerated by something but wasn't.

I'm using Unity 2022.1.11f1 on a Windows 10 Home PC (64-bit x64), with the latest commit (ada643f9129f9cfe309836a09e8ad498757c57f0).

Could you help me fix this? Thanks!

**Comment by kamyker** [comment]
Hi, thanks for details. No idea why file got removed as builder seems to copy it correctly. Should be fixed with https://github.com/kamyker/supabase-unity/commit/6f554949f119a6502fdf631dbf4487b658cc6173

**Comment by CoryParsnipson** [comment]
Nice, thanks!
